# lightning.pytorch==2.1.1
seed_everything: 42

trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: logs
      name: fire_scars
      version: "improved"
      log_graph: true
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 10
        min_delta: 1e-4
        mode: min
    - class_path: ModelCheckpoint
      init_args:
        monitor: val/loss
        save_top_k: 3
        mode: min
        filename: '{epoch}-{val_loss:.2f}'

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 25
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  enable_checkpointing: true
  default_root_dir: ./

data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 16
    num_workers: 12
    dataset_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_transform:
      - class_path: albumentations.RandomResizedCrop
        init_args:
          height: 256
          width: 256
          scale: [0.8, 1.0]
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.VerticalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.RandomRotate90
        init_args:
          p: 0.5
      - class_path: albumentations.RandomBrightnessContrast
        init_args:
          p: 0.5
      - class_path: albumentations.GaussNoise
        init_args:
          p: 0.2
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 256
          width: 256
      - class_path: ToTensorV2
    no_data_replace: 0
    no_label_replace: -1
    train_data_root: datasets/fire_scars_train_val/train
    train_label_data_root: datasets/fire_scars_train_val/train
    val_data_root: datasets/fire_scars_train_val/validation
    val_label_data_root: datasets/fire_scars_train_val/validation
    test_data_root: datasets/fire_scars_train_val/validation
    test_label_data_root: datasets/fire_scars_train_val/validation
    img_grep: "*_merged.tif"
    label_grep: "*.mask.tif"
    means: [0.485, 0.456, 0.406, 0.4, 0.4, 0.4]
    stds: [0.229, 0.224, 0.225, 0.2, 0.2, 0.2]
    num_classes: 2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: UperNetDecoder  # Changed to UperNetDecoder which is available in terratorch
      pretrained: true
      backbone: prithvi_vit_100
      decoder_channels: 16
      in_channels: 6
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 2
      head_dropout: 0.2
      decoder_num_convs: 3
      head_channel_list:
        - 16
        - 8
    loss: dice_ce  # Changed to dice_ce which is commonly available
    plot_on_val: 20
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    model_factory: PrithviModelFactory
    tiled_inference_parameters:
      h_crop: 1024
      h_stride: 768
      w_crop: 1024
      w_stride: 768
      average_patches: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]

lr_scheduler:
  class_path: OneCycleLR
  init_args:
    max_lr: 0.001
    epochs: 100
    steps_per_epoch: 500
    pct_start: 0.3
    div_factor: 25
    final_div_factor: 1e4