# lightning.pytorch==2.1.1
seed_everything: 42  # Set a common seed for reproducibility
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: logs
      name: fire_scars
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 3  # Increased patience for more epochs without improvement
    - class_path: ModelCheckpoint  # Save the best model based on validation loss
      init_args:
        monitor: val/loss
        save_top_k: 1
        mode: min

  max_epochs: 20  # Increased max epochs for better training
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: ./

data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 8  # Increased batch size for better gradient estimates
    num_workers: 16  # Increased workers for faster data loading
    dataset_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5  # Use a probability of 0.5 for flipping
      - class_path: albumentations.ColorJitter  # Added for more variability
        init_args:
          brightness: 0.1
          contrast: 0.1
          saturation: 0.1
          hue: 0.1
      - class_path: ToTensorV2
    no_data_replace: 0
    no_label_replace: -1
    train_data_root: datasets/fire_scars_train_val/train
    train_label_data_root: datasets/fire_scars_train_val/train
    val_data_root: datasets/fire_scars_train_val/validation
    val_label_data_root: datasets/fire_scars_train_val/validation
    test_data_root: datasets/fire_scars_train_val/validation
    test_label_data_root: datasets/fire_scars_train_val/validation
    img_grep: "*_merged.tif"
    label_grep: "*.mask.tif"
    means:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
    stds:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
    num_classes: 2  # Ensure this matches your dataset

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: FCNDecoder
      pretrained: true
      backbone: prithvi_vit_100
      decoder_channels: 8
      in_channels: 6
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 2
      head_dropout: 0.2  # Slightly increased dropout for regularization
      decoder_num_convs: 3  # Increased convolution layers in decoder
      head_channel_list:
        - 16  # Increased channel size for better feature representation
    loss: dice
    plot_on_val: 10
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    model_factory: PrithviModelFactory
    tiled_inference_parameters:
      h_crop: 512
      h_stride: 256  # Reduced stride for better overlap
      w_crop: 512
      w_stride: 256
      average_patches: true
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001  # Reduced learning rate for finer adjustments
    weight_decay: 0.001  # Reduced weight decay for better generalization
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    patience: 5  # Allow more epochs before reducing LR